### PR TITLE
Load old programs

### LINKED ISSUE #349: Load old programs
VPL 1.4 should be able to load VPL 1.3 programs

### PR DESCRIPTION
**Pull request by sampla**
Fixes #349

### CODE REVIEW

**Comment by stephanemagnenat** [comment]
Thanks!

**Comment by motib** [comment]
This is much appreciated, but ... I couldn't get it to work on Windows. Just to be sure: I downloaded the latest nightly build (bce6a19). Is this the correct build for fixing this issue?
Moti

**Comment by cbarraud** [comment]
Shouldn't we wait until tomorrow to have a nightly build ? Or compile it ourselves ?

**Comment by motib** [comment]
I have no problem waiting. Since there hasn't been a Windows build for over two months, I just assumed that the 1.2.15 build included this fix.

**Comment by cbarraud** [comment]
I was not sure either ;o) We are working on this buildfarm, normally it's fixed. We will keep you in the loop.

**Comment by mbonani** [comment]
Hello,
So I confirm we put alive the build-farm.  Last changes was not include in
the nightly built from 01.02.15.
We just manually launch the script now, so you can access to last changes
downloading the last build of 02.02.15 13:53
Script should work now every night as before around 1.am

Thank you Dany




*Bonani Michael*
Tél.: +41 (0) 21 693 78 69
Mobile: +41 (0) 76 349 72 14

Association Mobsya
1023 Crissier
www.mobsya.org


2015-02-02 12:14 GMT+01:00 cbarraud <notifications@github.com>:

**Comment by motib** [comment]
Hi,
I tried running last night's build, but unfortunately there were bugs in the first three VPL programs I tried to run. (The programs are from the VPL tutorial https://aseba.wdfiles.com/local--files/en:thymioprogram/thymio-vpl-tutorial-en.zip.)
Moti

1. likes.asel: Translation of proximity sensors switched the meaning of red/white -> white/black.
2. tap-on-off.aesl: Tap block causes translation to fail.
3. count-to-four.aesl: Crashes VPL.

**Comment by stephanemagnenat** [comment]
Pull request #355 should fix this. Feel free to test tomorrow with latest build.

**Comment by motib** [comment]
I checked out most of the program from the VPL tutorial and they work.
Thanks!!!

**Comment by sampla** [comment]
Great! I am really happy that it works.

**Pull request merged**
